name: calc_inv
description: "A new Flutter project."
publish_to: "none"
version: 0.1.0

environment:
  sdk: ^3.9.2

dependencies:
  flutter:
    sdk: flutter
  flutter_launcher_icons: ^0.14.4
  http: ^1.6.0
  intl: ^0.20.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  msix: ^3.16.12

flutter:
  uses-material-design: true
  assets:
    - assets/icons/X5.png
    - assets/icons/MDMG.png
    - assets/icons/NVTK.png
    - assets/icons/GMKN.png
    - assets/icons/PLZL.png
    - assets/icons/SBERP.png
    - assets/icons/CHMF.png
    - assets/icons/TATNP.png
    - assets/icons/PHOR.png
    - assets/icons/YDEX.png

msix_config:
  display_name: Calc App
  publisher_display_name: Company Name
  identity_name: company.suite.flutterapp
  msix_version: 1.0.1.0
  capabilities: internetClient

flutter_launcher_icons:
  image_path_android: "assets/icons/stock-market.png"
  android: true
  windows:
    generate: true
    image_path: "assets/icons/stock-market.png"
    icon_size: 48 # min:48, max:256, default: 48
